[package]
name = "holeio_modern"
version = "0.1.0"
edition = "2021"
authors = ["Hole.io Clone"]
description = "A modern Hole.io clone with procedural graphics"

[dependencies]
macroquad = "0.4"
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
